### ISSUE TITLE
Couldn't run python_demos examples for simulation [Question]: 

### ISSUE THREAD

**Issue by Yaru-Gu** [Interbotix/interbotix_ros_crawlers#6]
### Question

Hi, 
I was trying to run _python_demos_ for simulations on the interbotix hexapod platform. I followed the procedures specified in [issues/2#issuecomment-920217788](https://github.com/Interbotix/interbotix_ros_crawlers/issues/2#issuecomment-920217788) to install the ROS packages. I was able to launch `xshexapod_control.launch` file and arouse rviz. However, I run into the following error with python demos `push_ups.py`, `roll_pitch_combo.py`, `translate_xy_combo.py`, `usage.py`, `walk_in_square.py`, and `wave_front_legs.py`,
_TypeError: identity() got an unexpected keyword argument 'like'_

For the rest two python demos, `move_in_place.py` and `uneven_terrain.py`, the error does not come up, but the robot is not moving at all. 

### Robot Model

pxmark4

### Operating System

Ubuntu 20.04

**Comment by LSinterbotix** [comment]
@Yaru-Gu the TypeError you recieved is likely because you need to update your numpy version. If running Noetic, try running the command `pip3 install numpy --upgrade`.

If you haven't already, change the `robot_name` parameter to `pxmark4` when you [instantiate the InterbotixHexapodXS object](https://github.com/Interbotix/interbotix_ros_crawlers/blob/0b91098dfcee7cbe0403fe847828cbbe02bb3f24/interbotix_ros_xshexapods/examples/python_demos/uneven_terrain.py#L9) in the Python script, else the controller will look for the services under the wrong namespace.

Let me know if that works for you - if not, we can try to dig a little deeper.

**Comment by Yaru-Gu** [comment]
@LSinterbotix Thank you very much. Everything is working now.
